import type {
  User,
  Project,
  Task,
  TeamMember,
  ActivityItem,
  DashboardStats,
} from "@/types";

// ---- Mock Current User ----
export const mockCurrentUser: User = {
  id: "usr-001",
  name: "Jamshed Iqbal",
  email: "jamshed@projex.io",
  avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamshed",
  role: "admin",
  department: "Engineering",
  joinedAt: "2024-01-15",
  status: "active",
};

// ---- Mock Team Members ----
export const mockTeamMembers: TeamMember[] = [
  {
    id: "usr-001",
    name: "Jamshed Iqbal",
    email: "jamshed@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamshed",
    role: "admin",
    department: "Engineering",
    joinedAt: "2024-01-15",
    status: "active",
    tasksAssigned: 12,
    tasksCompleted: 9,
    projects: ["proj-001", "proj-002", "proj-003"],
  },
  {
    id: "usr-002",
    name: "Sarah Chen",
    email: "sarah@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sarah",
    role: "manager",
    department: "Design",
    joinedAt: "2024-02-10",
    status: "active",
    tasksAssigned: 8,
    tasksCompleted: 6,
    projects: ["proj-001", "proj-004"],
  },
  {
    id: "usr-003",
    name: "Alex Rivera",
    email: "alex@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alex",
    role: "member",
    department: "Engineering",
    joinedAt: "2024-03-05",
    status: "away",
    tasksAssigned: 10,
    tasksCompleted: 7,
    projects: ["proj-002", "proj-003"],
  },
  {
    id: "usr-004",
    name: "Maria Gonzalez",
    email: "maria@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maria",
    role: "member",
    department: "Marketing",
    joinedAt: "2024-03-20",
    status: "active",
    tasksAssigned: 6,
    tasksCompleted: 5,
    projects: ["proj-004", "proj-005"],
  },
  {
    id: "usr-005",
    name: "James Wilson",
    email: "james@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=James",
    role: "member",
    department: "Engineering",
    joinedAt: "2024-04-01",
    status: "offline",
    tasksAssigned: 9,
    tasksCompleted: 4,
    projects: ["proj-001", "proj-002"],
  },
  {
    id: "usr-006",
    name: "Emily Park",
    email: "emily@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Emily",
    role: "manager",
    department: "Product",
    joinedAt: "2024-01-25",
    status: "active",
    tasksAssigned: 11,
    tasksCompleted: 10,
    projects: ["proj-003", "proj-005"],
  },
  {
    id: "usr-007",
    name: "David Kim",
    email: "david@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=David",
    role: "member",
    department: "Engineering",
    joinedAt: "2024-05-12",
    status: "active",
    tasksAssigned: 7,
    tasksCompleted: 3,
    projects: ["proj-001", "proj-003"],
  },
  {
    id: "usr-008",
    name: "Lisa Thompson",
    email: "lisa@projex.io",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lisa",
    role: "member",
    department: "Design",
    joinedAt: "2024-06-01",
    status: "away",
    tasksAssigned: 5,
    tasksCompleted: 4,
    projects: ["proj-004"],
  },
];

// ---- Mock Projects ----
export const mockProjects: Project[] = [
  {
    id: "proj-001",
    name: "Website Redesign",
    description: "Complete overhaul of the company website with modern UI/UX",
    status: "active",
    priority: "high",
    progress: 68,
    startDate: "2025-01-10",
    dueDate: "2025-04-30",
    teamMembers: ["usr-001", "usr-002", "usr-005", "usr-007"],
    tasksCount: 24,
    completedTasks: 16,
    createdAt: "2025-01-08",
    updatedAt: "2025-02-09",
    color: "#6366f1",
  },
  {
    id: "proj-002",
    name: "Mobile App v2",
    description:
      "Second major version of the mobile application with new features",
    status: "active",
    priority: "critical",
    progress: 42,
    startDate: "2025-01-20",
    dueDate: "2025-06-15",
    teamMembers: ["usr-001", "usr-003", "usr-005"],
    tasksCount: 36,
    completedTasks: 15,
    createdAt: "2025-01-18",
    updatedAt: "2025-02-08",
    color: "#f43f5e",
  },
  {
    id: "proj-003",
    name: "Analytics Dashboard",
    description:
      "Build comprehensive analytics dashboard for business insights",
    status: "active",
    priority: "medium",
    progress: 85,
    startDate: "2024-11-01",
    dueDate: "2025-03-01",
    teamMembers: ["usr-001", "usr-003", "usr-006", "usr-007"],
    tasksCount: 18,
    completedTasks: 15,
    createdAt: "2024-10-28",
    updatedAt: "2025-02-07",
    color: "#10b981",
  },
  {
    id: "proj-004",
    name: "Brand Identity Refresh",
    description: "Update brand guidelines, logos, and marketing materials",
    status: "on-hold",
    priority: "low",
    progress: 30,
    startDate: "2025-02-01",
    dueDate: "2025-05-30",
    teamMembers: ["usr-002", "usr-004", "usr-008"],
    tasksCount: 12,
    completedTasks: 4,
    createdAt: "2025-01-28",
    updatedAt: "2025-02-05",
    color: "#f59e0b",
  },
  {
    id: "proj-005",
    name: "API Gateway Migration",
    description: "Migrate existing APIs to new gateway infrastructure",
    status: "completed",
    priority: "high",
    progress: 100,
    startDate: "2024-09-15",
    dueDate: "2025-01-31",
    teamMembers: ["usr-004", "usr-006"],
    tasksCount: 20,
    completedTasks: 20,
    createdAt: "2024-09-10",
    updatedAt: "2025-01-30",
    color: "#8b5cf6",
  },
];

// ---- Mock Tasks ----
export const mockTasks: Task[] = [
  {
    id: "task-001",
    title: "Design new landing page",
    description:
      "Create wireframes and high-fidelity mockups for the new landing page",
    status: "done",
    priority: "high",
    projectId: "proj-001",
    projectName: "Website Redesign",
    assigneeId: "usr-002",
    assigneeName: "Sarah Chen",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sarah",
    tags: ["design", "ui/ux"],
    dueDate: "2025-02-15",
    createdAt: "2025-01-12",
    updatedAt: "2025-02-08",
  },
  {
    id: "task-002",
    title: "Implement authentication flow",
    description: "Build login, register, and password reset functionality",
    status: "in-progress",
    priority: "critical",
    projectId: "proj-001",
    projectName: "Website Redesign",
    assigneeId: "usr-001",
    assigneeName: "Jamshed Iqbal",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamshed",
    tags: ["frontend", "auth"],
    dueDate: "2025-02-20",
    createdAt: "2025-01-15",
    updatedAt: "2025-02-09",
  },
  {
    id: "task-003",
    title: "Set up CI/CD pipeline",
    description:
      "Configure GitHub Actions for automated testing and deployment",
    status: "todo",
    priority: "medium",
    projectId: "proj-002",
    projectName: "Mobile App v2",
    assigneeId: "usr-005",
    assigneeName: "James Wilson",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=James",
    tags: ["devops", "automation"],
    dueDate: "2025-02-25",
    createdAt: "2025-01-20",
    updatedAt: "2025-02-06",
  },
  {
    id: "task-004",
    title: "Create component library",
    description: "Build reusable React components with Storybook documentation",
    status: "in-review",
    priority: "high",
    projectId: "proj-001",
    projectName: "Website Redesign",
    assigneeId: "usr-007",
    assigneeName: "David Kim",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=David",
    tags: ["frontend", "components"],
    dueDate: "2025-02-18",
    createdAt: "2025-01-14",
    updatedAt: "2025-02-09",
  },
  {
    id: "task-005",
    title: "Database schema design",
    description: "Design and implement the new database schema for analytics",
    status: "done",
    priority: "high",
    projectId: "proj-003",
    projectName: "Analytics Dashboard",
    assigneeId: "usr-003",
    assigneeName: "Alex Rivera",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alex",
    tags: ["backend", "database"],
    dueDate: "2025-01-30",
    createdAt: "2024-11-05",
    updatedAt: "2025-01-28",
  },
  {
    id: "task-006",
    title: "User onboarding redesign",
    description: "Redesign the onboarding flow for new mobile app users",
    status: "in-progress",
    priority: "medium",
    projectId: "proj-002",
    projectName: "Mobile App v2",
    assigneeId: "usr-002",
    assigneeName: "Sarah Chen",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sarah",
    tags: ["design", "mobile"],
    dueDate: "2025-03-01",
    createdAt: "2025-01-22",
    updatedAt: "2025-02-07",
  },
  {
    id: "task-007",
    title: "Performance optimization",
    description: "Optimize page load times and reduce bundle size",
    status: "backlog",
    priority: "medium",
    projectId: "proj-001",
    projectName: "Website Redesign",
    assigneeId: "usr-001",
    assigneeName: "Jamshed Iqbal",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamshed",
    tags: ["performance", "frontend"],
    dueDate: "2025-03-15",
    createdAt: "2025-01-25",
    updatedAt: "2025-02-05",
  },
  {
    id: "task-008",
    title: "Write API documentation",
    description: "Document all REST API endpoints with examples and schemas",
    status: "todo",
    priority: "low",
    projectId: "proj-003",
    projectName: "Analytics Dashboard",
    assigneeId: "usr-006",
    assigneeName: "Emily Park",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Emily",
    tags: ["documentation", "api"],
    dueDate: "2025-02-28",
    createdAt: "2025-01-20",
    updatedAt: "2025-02-04",
  },
  {
    id: "task-009",
    title: "Push notification system",
    description: "Implement push notifications for mobile app with Firebase",
    status: "backlog",
    priority: "high",
    projectId: "proj-002",
    projectName: "Mobile App v2",
    assigneeId: "usr-003",
    assigneeName: "Alex Rivera",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alex",
    tags: ["mobile", "backend"],
    dueDate: "2025-04-01",
    createdAt: "2025-01-28",
    updatedAt: "2025-02-03",
  },
  {
    id: "task-010",
    title: "Social media campaign",
    description: "Plan and execute social media campaign for brand refresh",
    status: "todo",
    priority: "medium",
    projectId: "proj-004",
    projectName: "Brand Identity Refresh",
    assigneeId: "usr-004",
    assigneeName: "Maria Gonzalez",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maria",
    tags: ["marketing", "social"],
    dueDate: "2025-03-15",
    createdAt: "2025-02-01",
    updatedAt: "2025-02-05",
  },
  {
    id: "task-011",
    title: "Responsive navigation",
    description: "Build responsive sidebar and mobile navigation components",
    status: "in-progress",
    priority: "high",
    projectId: "proj-001",
    projectName: "Website Redesign",
    assigneeId: "usr-005",
    assigneeName: "James Wilson",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=James",
    tags: ["frontend", "responsive"],
    dueDate: "2025-02-22",
    createdAt: "2025-01-18",
    updatedAt: "2025-02-09",
  },
  {
    id: "task-012",
    title: "Data visualization widgets",
    description:
      "Create interactive charts and graphs for the analytics dashboard",
    status: "in-review",
    priority: "high",
    projectId: "proj-003",
    projectName: "Analytics Dashboard",
    assigneeId: "usr-007",
    assigneeName: "David Kim",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=David",
    tags: ["frontend", "charts"],
    dueDate: "2025-02-15",
    createdAt: "2024-12-10",
    updatedAt: "2025-02-08",
  },
  {
    id: "task-013",
    title: "Logo variations design",
    description: "Create logo variations for different use cases and platforms",
    status: "in-progress",
    priority: "medium",
    projectId: "proj-004",
    projectName: "Brand Identity Refresh",
    assigneeId: "usr-008",
    assigneeName: "Lisa Thompson",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lisa",
    tags: ["design", "branding"],
    dueDate: "2025-03-10",
    createdAt: "2025-02-02",
    updatedAt: "2025-02-07",
  },
  {
    id: "task-014",
    title: "Unit test coverage",
    description: "Increase unit test coverage to 80% across all modules",
    status: "todo",
    priority: "medium",
    projectId: "proj-002",
    projectName: "Mobile App v2",
    assigneeId: "usr-001",
    assigneeName: "Jamshed Iqbal",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamshed",
    tags: ["testing", "quality"],
    dueDate: "2025-03-20",
    createdAt: "2025-01-25",
    updatedAt: "2025-02-04",
  },
  {
    id: "task-015",
    title: "Email template system",
    description: "Build dynamic email template engine for marketing campaigns",
    status: "backlog",
    priority: "low",
    projectId: "proj-004",
    projectName: "Brand Identity Refresh",
    assigneeId: "usr-004",
    assigneeName: "Maria Gonzalez",
    assigneeAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maria",
    tags: ["marketing", "email"],
    dueDate: "2025-04-15",
    createdAt: "2025-02-03",
    updatedAt: "2025-02-06",
  },
];

// ---- Mock Activity Feed ----
export const mockActivity: ActivityItem[] = [
  {
    id: "act-001",
    user: "Jamshed Iqbal",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamshed",
    action: "completed task",
    target: "Implement authentication flow",
    timestamp: "2 minutes ago",
  },
  {
    id: "act-002",
    user: "Sarah Chen",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sarah",
    action: "created project",
    target: "Brand Identity Refresh",
    timestamp: "15 minutes ago",
  },
  {
    id: "act-003",
    user: "David Kim",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=David",
    action: "moved task to review",
    target: "Data visualization widgets",
    timestamp: "1 hour ago",
  },
  {
    id: "act-004",
    user: "Alex Rivera",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alex",
    action: "commented on",
    target: "Push notification system",
    timestamp: "2 hours ago",
  },
  {
    id: "act-005",
    user: "Emily Park",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Emily",
    action: "updated priority of",
    target: "API Gateway Migration",
    timestamp: "3 hours ago",
  },
  {
    id: "act-006",
    user: "James Wilson",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=James",
    action: "assigned task",
    target: "Set up CI/CD pipeline",
    timestamp: "5 hours ago",
  },
  {
    id: "act-007",
    user: "Maria Gonzalez",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maria",
    action: "uploaded files to",
    target: "Social media campaign",
    timestamp: "Yesterday",
  },
  {
    id: "act-008",
    user: "Lisa Thompson",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lisa",
    action: "started working on",
    target: "Logo variations design",
    timestamp: "Yesterday",
  },
];

// ---- Mock Dashboard Stats ----
export const mockDashboardStats: DashboardStats = {
  totalProjects: 5,
  activeProjects: 3,
  totalTasks: 15,
  completedTasks: 7,
  teamMembers: 8,
  overdueTasks: 2,
};

// ---- Chart Data ----
export const tasksByStatusData = [
  { status: "Backlog", count: 3, fill: "var(--color-chart-1)" },
  { status: "To Do", count: 4, fill: "var(--color-chart-2)" },
  { status: "In Progress", count: 4, fill: "var(--color-chart-3)" },
  { status: "In Review", count: 2, fill: "var(--color-chart-4)" },
  { status: "Done", count: 2, fill: "var(--color-chart-5)" },
];

export const weeklyProgressData = [
  { day: "Mon", completed: 3, created: 5 },
  { day: "Tue", completed: 5, created: 4 },
  { day: "Wed", completed: 2, created: 6 },
  { day: "Thu", completed: 7, created: 3 },
  { day: "Fri", completed: 4, created: 2 },
  { day: "Sat", completed: 1, created: 1 },
  { day: "Sun", completed: 0, created: 0 },
];

export const projectProgressData = mockProjects.map((p) => ({
  name: p.name,
  progress: p.progress,
  fill: p.color,
}));
